name: ImgFT
channels:
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aiodns=3.5.0=py313h06a4308_1
  - aiohappyeyeballs=2.6.1=py313h06a4308_0
  - aiohttp=3.13.2=py313hee96239_0
  - aiosignal=1.4.0=py313h06a4308_0
  - anyio=4.10.0=py313h06a4308_0
  - aom=3.12.1=h7934f7d_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py313hee96239_0
  - arrow-cpp=21.0.0=hac1acdb_1
  - asttokens=3.0.0=py313h06a4308_0
  - async-lru=2.0.5=py313h06a4308_0
  - attrs=25.4.0=py313h06a4308_2
  - aws-c-auth=0.9.0=hb25bd0a_2
  - aws-c-cal=0.9.2=h3ff94e8_1
  - aws-c-common=0.12.4=hb25bd0a_0
  - aws-c-compression=0.3.1=hb25bd0a_2
  - aws-c-event-stream=0.5.6=hb25bd0a_0
  - aws-c-http=0.10.4=hb25bd0a_0
  - aws-c-io=0.21.4=h3eb0749_0
  - aws-c-mqtt=0.13.3=hb25bd0a_0
  - aws-c-s3=0.8.7=h3ff94e8_0
  - aws-c-sdkutils=0.2.4=hb25bd0a_1
  - aws-checksums=0.2.7=hb25bd0a_1
  - aws-crt-cpp=0.34.0=h7934f7d_0
  - aws-sdk-cpp=1.11.638=hac3f51a_0
  - babel=2.17.0=py313h06a4308_0
  - beautifulsoup4=4.14.2=py313h06a4308_0
  - blas=1.0=mkl
  - bleach=6.3.0=py313h06a4308_0
  - bottleneck=1.4.2=py313haa0f9ac_1
  - brotlicffi=1.2.0.0=py313h7354ed3_0
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.12.2=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - certifi=2025.11.12=py313h06a4308_0
  - cffi=2.0.0=py313h4eded50_1
  - charset-normalizer=3.4.4=py313h06a4308_0
  - comm=0.2.3=py313h06a4308_0
  - contourpy=1.3.3=py313hdb19cb5_0
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - datasets=4.4.1=py313h06a4308_0
  - dav1d=1.2.1=h5eee18b_0
  - debugpy=1.8.16=py313hbdd6827_1
  - decorator=5.2.1=py313h06a4308_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - dill=0.4.0=py313h06a4308_0
  - executing=2.2.1=py313h06a4308_0
  - expat=2.7.3=h7354ed3_4
  - filelock=3.20.0=py313h06a4308_0
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.61.0=py313h47b2149_0
  - freetype=2.13.3=h4a9f257_0
  - fribidi=1.0.10=h7b6447c_0
  - frozenlist=1.8.0=py313hbdd6827_0
  - fsspec=2025.10.0=py313h7040dfc_0
  - gettext=0.21.0=hedfda30_2
  - gflags=2.2.2=h6a678d5_1
  - glog=0.5.0=h6a678d5_1
  - graphite2=1.3.14=h295c915_1
  - h11=0.16.0=py313h06a4308_1
  - harfbuzz=10.2.0=hdfddeaa_1
  - hf-xet=1.1.8=py313h84c0859_0
  - html5lib=1.1=pyhd3eb1b0_0
  - httpcore=1.0.9=py313h06a4308_0
  - httpx=0.28.1=py313h06a4308_1
  - huggingface_hub=0.34.4=py313h06a4308_0
  - icu=73.1=h6a678d5_0
  - idna=3.11=py313h06a4308_0
  - intel-openmp=2025.0.0=h06a4308_1171
  - ipykernel=6.31.0=py313h7040dfc_0
  - ipython=9.7.0=py313h06a4308_0
  - ipython_pygments_lexers=1.1.1=py313h06a4308_0
  - jansson=2.14=h5eee18b_1
  - jedi=0.19.2=py313h06a4308_0
  - jinja2=3.1.6=py313h06a4308_0
  - jpeg=9f=h5ce9db8_0
  - json5=0.12.1=py313h06a4308_0
  - jsonschema=4.25.0=py313h06a4308_1
  - jsonschema-specifications=2025.9.1=py313h06a4308_0
  - jupyter-lsp=2.2.5=py313h06a4308_0
  - jupyter_client=8.6.3=py313h06a4308_1
  - jupyter_core=5.9.1=py313h06a4308_0
  - jupyter_events=0.12.0=py313h06a4308_0
  - jupyter_server=2.17.0=py313h06a4308_0
  - jupyter_server_terminals=0.5.3=py313h06a4308_0
  - jupyterlab=4.5.0=py313h06a4308_0
  - jupyterlab_pygments=0.3.0=py313h06a4308_0
  - jupyterlab_server=2.28.0=py313h06a4308_0
  - kiwisolver=1.4.9=py313h24d9097_0
  - lcms2=2.17=heab6991_0
  - ld_impl_linux-64=2.44=h153f514_2
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libavif=1.3.0=h3539ee5_0
  - libbrotlicommon=1.0.9=h5eee18b_9
  - libbrotlidec=1.0.9=h5eee18b_9
  - libbrotlienc=1.0.9=h5eee18b_9
  - libcups=2.4.15=hbe4054b_0
  - libcurl=8.16.0=heebcbe5_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libexpat=2.7.3=h7354ed3_4
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgfortran=15.2.0=h166f726_7
  - libgfortran-ng=15.2.0=h166f726_7
  - libgfortran5=15.2.0=hc633d37_7
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.4=h77a78f3_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=15.2.0=h4751f2c_7
  - libgrpc=1.71.0=h2d74bed_0
  - libhwloc=2.12.1=default_hf1bbc79_1000
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.8=hf80d704_0
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libmpdec=4.0.0=h5eee18b_0
  - libnghttp2=1.67.1=h697f920_0
  - libopengl=1.7.0=h5eee18b_2
  - libopenjpeg=2.5.4=hee96239_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.50=h2ed474d_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libre2-11=2024.07.02=h6a678d5_0
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libthrift=0.22.0=hd8eb582_0
  - libtiff=4.7.1=h029b1ac_0
  - libunistring=1.3=hb25bd0a_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libwebp-base=1.6.0=hb7bb969_0
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.9=h2c43086_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - markupsafe=3.0.2=py313h5eee18b_0
  - matplotlib=3.10.7=py313h06a4308_0
  - matplotlib-base=3.10.7=py313h8a257da_0
  - matplotlib-inline=0.2.1=py313h06a4308_0
  - mesalib=25.1.5=h31e3550_0
  - mistune=3.1.2=py313h06a4308_0
  - mkl=2025.0.0=hacee8c2_941
  - mkl-service=2.5.2=py313hacdc0fc_0
  - mkl_fft=2.1.1=py313h57662e1_0
  - mkl_random=1.3.0=py313h23c847b_0
  - multidict=6.7.0=py313hee96239_0
  - multiprocess=0.70.18=py313h06a4308_0
  - mysql-common=9.3.0=h9e076cb_4
  - mysql-libs=9.3.0=h6ecde68_4
  - nbclient=0.10.2=py313h06a4308_0
  - nbconvert-core=7.16.6=py313h06a4308_0
  - nbformat=5.10.4=py313h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py313h06a4308_0
  - notebook=7.5.0=py313h06a4308_0
  - notebook-shim=0.2.4=py313h06a4308_0
  - numexpr=2.14.1=py313h41d4191_0
  - numpy=2.3.5=py313h08c6c3d_0
  - numpy-base=2.3.5=py313h00548fb_0
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - orc=2.2.0=h372e9aa_0
  - packaging=25.0=py313h06a4308_1
  - pandas=2.3.3=py313h23c847b_1
  - pandocfilters=1.5.1=py313h06a4308_0
  - parso=0.8.5=py313h06a4308_0
  - pcre2=10.46=hf426167_0
  - pexpect=4.9.0=py313h06a4308_1
  - pillow=12.0.0=py313h3b88751_1
  - pip=25.3=pyhc872135_0
  - pixman=0.46.4=h7934f7d_0
  - platformdirs=4.5.0=py313h06a4308_0
  - prometheus_client=0.21.1=py313h06a4308_0
  - prompt-toolkit=3.0.52=py313h06a4308_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - propcache=0.4.1=py313h47b2149_0
  - protobuf=5.29.3=py313he621ea3_0
  - psutil=7.0.0=py313hee96239_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_3
  - pure_eval=0.2.3=py313h06a4308_0
  - pyarrow=21.0.0=py313h86c3e14_1
  - pycares=4.10.0=py313ha137689_0
  - pycparser=2.23=py313h06a4308_0
  - pygments=2.19.2=py313h06a4308_0
  - pyparsing=3.2.5=py313h06a4308_0
  - pyqt=6.9.1=py313hc79087c_0
  - pyqt6-sip=13.10.2=py313hee96239_0
  - pysocks=1.7.1=py313h06a4308_1
  - python=3.13.11=hcf712cf_100_cp313
  - python-dateutil=2.9.0post0=py313h06a4308_2
  - python-fastjsonschema=2.21.2=py313h06a4308_0
  - python-json-logger=4.0.0=py313h06a4308_0
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python-xxhash=3.5.0=py313h5eee18b_0
  - python_abi=3.13=3_cp313
  - pytz=2025.2=py313h06a4308_0
  - pyyaml=6.0.3=py313h591646f_0
  - pyzmq=27.1.0=py313hcf8288c_1
  - qtbase=6.9.2=hd13baf8_5
  - qtdeclarative=6.9.2=h55666de_1
  - qtsvg=6.9.2=h75a08ff_1
  - qttools=6.9.2=hc856bc8_1
  - qtwayland=6.9.2=h9f1b7ec_1
  - qtwebchannel=6.9.2=hbdd6827_1
  - qtwebsockets=6.9.2=hbdd6827_1
  - re2=2024.07.02=hdb19cb5_0
  - readline=8.3=hc2a1206_0
  - referencing=0.37.0=py313h06a4308_0
  - regex=2025.11.3=py313h47b2149_0
  - requests=2.32.5=py313h06a4308_1
  - rfc3339-validator=0.1.4=py313h06a4308_0
  - rfc3986-validator=0.1.1=py313h06a4308_0
  - rpds-py=0.28.0=py313h498d7c9_0
  - ruff=0.12.0=py313hc6f7160_0
  - s2n=1.5.14=hdbd6064_0
  - safetensors=0.6.2=py313h498d7c9_0
  - scipy=1.16.3=py313h33bc11c_0
  - send2trash=1.8.2=py313h06a4308_1
  - setuptools=80.9.0=py313h06a4308_0
  - sip=6.12.0=py313h7934f7d_0
  - six=1.17.0=py313h06a4308_0
  - snappy=1.2.1=h6a678d5_0
  - sniffio=1.3.1=py313h06a4308_0
  - soupsieve=2.5=py313h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.51.0=h2a70700_0
  - stack_data=0.6.3=py313h06a4308_0
  - tbb=2022.3.0=h698db13_0
  - tbb-devel=2022.3.0=h698db13_0
  - terminado=0.18.1=py313h06a4308_0
  - tinycss2=1.4.0=py313h06a4308_0
  - tk=8.6.15=h54e0aa7_0
  - tokenizers=0.21.0=py313hb8e4a85_0
  - tornado=6.5.1=py313h5eee18b_0
  - tqdm=4.67.1=py313h7040dfc_1
  - traitlets=5.14.3=py313h06a4308_0
  - transformers=4.49.0=py313h06a4308_0
  - typing-extensions=4.15.0=py313h06a4308_0
  - typing_extensions=4.15.0=py313h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - urllib3=2.6.1=py313h06a4308_0
  - utf8proc=2.6.1=h5eee18b_1
  - uvloop=0.22.1=py313h939ff40_1
  - wayland=1.24.0=hdac8c69_0
  - wcwidth=0.2.13=py313h06a4308_0
  - webencodings=0.5.1=py313h06a4308_2
  - websocket-client=1.8.0=py313h06a4308_0
  - wheel=0.45.1=py313h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xxhash=0.8.0=h7f8727e_3
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - yarl=1.22.0=py313hee96239_0
  - zeromq=4.3.5=hb0a5e54_1
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
prefix: /jet/home/tho2/.conda/envs/ImgFT
